#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          vpnbridge
# Required-Start:    $remote_fs $local_fs $syslog $networking
# Required-Stop:     $remote_fs $local_fs $syslog
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SoftEther VPN Bridge
# Description:
### END INIT INFO
DAEMON=/usr/local/vpnbridge/vpnbridge
LOCK=/var/lock/subsys/vpnbridge
test -x $DAEMON || exit 0
case "$1" in
start)
ip route add 52.38.92.17 via 192.168.2.1 dev eth0
#ip link set eth1 down
#ip addr add 0.0.0.0/24 dev eth1
#ip link set eth1 up
$DAEMON start
touch $LOCK
sleep 5
brctl addbr br0
brctl addif br0 tap_svpn
sleep 10
brctl addif br0 eth1
ip link set br0 up
dhclient br0
;;
stop)
ip link set br0 down
brctl delbr br0
$DAEMON stop
rm $LOCK
;;
restart)
ip link set br0 down
brctl delbr br0
$DAEMON stop
sleep 3
#ip link set eth1 down
#ip addr add 0.0.0.0/24 dev eth1
#ip link set eth1 up
$DAEMON start
sleep 5
brctl addbr br0
brctl addif br0 tap_svpn
sleep 10
brctl addif br0 eth1
ip link set br0 up
dhclient br0
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac
exit 0
