#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          vpnbridge
# Required-Start:    $remote_fs $local_fs $syslog $networking
# Required-Stop:     $remote_fs $local_fs $syslog
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SoftEther VPN Bridge
# Description:
### END INIT INFO
DAEMON=/usr/local/vpnbridge/vpnbridge
LOCK=/var/lock/subsys/vpnbridge
test -x $DAEMON || exit 0
case "$1" in
start)
    # Change ip address based on local mechine setting
    ip route add 52.38.92.17 via 192.168.2.1 dev eth0
    #ip link set eth1 down
    #ip addr add 0.0.0.0/24 dev eth1
    #ip link set eth1 up
    $DAEMON start
    touch $LOCK
    sleep 5
    while [ -z "$(ip link | grep svpn)" ]; do
        sleep 5
    done
    brctl addif br0 svpn
    ;;
stop)
    brctl delif br0 svpn
    $DAEMON stop
    rm $LOCK
    ;;
restart)
    brctl delif br0 svpn
    $DAEMON stop
    sleep 3
    #ip link set eth1 down
    #ip addr add 0.0.0.0/24 dev eth1
    #ip link set eth1 up
    $DAEMON start
    while [ -z "$(ip link | grep svpn)" ]; do
        sleep 5
    done
    brctl addif br0 svpn
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
