#!/bin/bash

# These should be tuned based on your system
PLAYGROUNDLOCATION=~/git/thingweb-playground/packages/assertions/
NEWCSVPATH=../../../../../thingweb-playground/packages/assertions/assertions-csv/manual.csv
EVENTPATH=../../../../data/input_2022/TD
# These are per implementation

IMPLEMENTATION=dart_wot
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=Ditto
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=ECLASS
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=editdor
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=fischertechnik-factory-simulator
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=flask-tum
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=Fujitsu
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=hitachi-esp-idf
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=hitachi-node-red
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=hitachi-nodegen
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=huawei
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=intel-nodejs
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=intel-proxy
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=intel-wot-ha
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=mqtt-experimental
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=NHK
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=node-wot
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=Oracle
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=oracle-wt
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=philips-hue
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=Playground
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=saywot
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=sdf-wot-converter
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=siemens-logilab
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=TinyIoT
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=VAIMEE
node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md

IMPLEMENTATION=WebThings
# no manual csv
#node $PLAYGROUNDLOCATION/generate-changelog.js $EVENTPATH/$IMPLEMENTATION/$IMPLEMENTATION.csv $NEWCSVPATH > $IMPLEMENTATION.md
